#SPDX-License-Identifier: MIT-0
---
# tasks file for postgres_replication
# Установка python-пакетов для модулей psql
#  - name: install base tools
#    apt:
#      name:
#        - python3-pexpect
#        - python3-psycopg2
#      state: present
#      update_cache: true

#CREATE USER replicator WITH REPLICATION Encrypted PASSWORD 'Otus2022!';
#  - name: Create replicator user
#    become: yes
#    become_user: postgres
#    community.postgresql.postgresql_user:
#      name: replicator
#      password: '{{ replicator_password }}'
#      state: present
#      role_attr_flags: REPLICATION 
#    ignore_errors: yes
#    when: (inventory_hostname == "node1")
    
  - name: Создать пользователя для физической репликации
    community.postgresql.postgresql_user:
      name: replicator
      password: '{{ replicator_password }}'
      role_attr_flags: "REPLICATION,LOGIN" # Обязательно REPLICATION
      state: present
    become: true
    become_user: postgres 
    when: (inventory_hostname == "node1")

  - name: Разрешить подключения для репликации в pg_hba.conf
    community.postgresql.postgresql_pg_hba:
      dest: "/etc/postgresql/14/main/pg_hba.conf" 
      contype: host
      users: replicator
      source: "192.168.57.0/24" # IP или подсеть Slave-сервера
      databases: replication
      method: scram-sha-256 
      state: present
#     notify: Restart PostgreSQL  
  

  #Останавливаем postgresql-14 на хосте node2
  - name: stop postgresql-server on node2
    service: 
      name: postgresql
      state: stopped
    when: (inventory_hostname == "node2")

  #Копируем конфигурационный файл postgresql.conf
  - name: copy postgresql.conf
    template:
      src: postgresql.conf.j2
      dest: /etc/postgresql/14/main/postgresql.conf
      owner: postgres
      group: postgres
      mode: '0600'
    when: (inventory_hostname == "node1")
  
  #Копируем конфигурационный файл pg_hba.conf
  - name: copy pg_hba.conf
    template:
      src: pg_hba.conf.j2
      dest: /etc/postgresql/14/main/pg_hba.conf
      owner: postgres
      group: postgres
      mode: '0600'
    when: (inventory_hostname == "node1")


   #Перезапускаем службу  postgresql-14
  - name: restart postgresql-server on node1
    service: 
      name: postgresql
      state: restarted
    when: (inventory_hostname == "node1")

  #Удаляем содержимое каталога /var/lib/postgresql/14/main/
  - name: Remove files from data catalog
    file:
      path: /var/lib/postgresql/14/main/
      state: absent
    when: (inventory_hostname == "node2")

  #Копируем данные с node1 на node2
  - name: copy files from master to slave
    become_user: postgres
    expect:
      command: 'pg_basebackup -h {{ master_ip }} -U  {{ replication_user }} -p 5432 -D /var/lib/postgresql/14/main/ -R -P'
      responses: 
        '.*Password*': "{{ replicator_password }}"
    when: (inventory_hostname == "node2")

  #Копируем конфигурационный файл postgresql.conf
  - name: copy postgresql.conf
    template:
      src: postgresql.conf.j2
      dest:  /etc/postgresql/14/main/postgresql.conf
      owner: postgres
      group: postgres
      mode: '0600'
    when: (inventory_hostname == "node2")

  #Копируем конфигурационный файл pg_hba.conf
  - name: copy pg_hba.conf
    template:
      src: pg_hba.conf.j2
      dest:  /etc/postgresql/14/main/pg_hba.conf
      owner: postgres
      group: postgres
      mode: '0600'
    when: (inventory_hostname == "node2")
   
  #Запускаем службу postgresql-14 на хосте node2
  - name: start postgresql-server on node2
    service: 
      name: postgresql
      state: started
    when: (inventory_hostname == "node2")

